//
//  UIColor+APPAdditions.swift
//
//  Generated by Zeplin on 4/14/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func appDarkSlateBlueColor() -> UIColor {
		return UIColor(red: 32.0 / 255.0, green: 70.0 / 255.0, blue: 113.0 / 255.0, alpha: 1.0)
	}

    class func appTintBlueColor() -> UIColor {
        return UIColor(red: 45.0 / 255.0, green: 97.0 / 255.0, blue: 155.0 / 255.0, alpha: 1.0)
    }
}
